# nrf52840-nosd on all targets. Flash settings_reset when switching layouts.
# Daily left: toucan_left_no_studio.
---
include:
  - board: xiao_ble//zmk
    shield: toucan_left rgbled_adapter
    snippet: nrf52840-nosd studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: toucan_left_bare_studio
  - board: xiao_ble//zmk
    shield: toucan_left rgbled_adapter nice_view_gem
    snippet: nrf52840-nosd
    artifact-name: toucan_left_no_studio
  - board: xiao_ble//zmk
    shield: toucan_left rgbled_adapter nice_view_gem
    snippet: nrf52840-nosd zmk-usb-logging
    cmake-args: >-
      -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
      -DCONFIG_ZMK_LOG_LEVEL_DBG=y
      -DCONFIG_DISPLAY_LOG_LEVEL_DBG=y
    artifact-name: toucan_left_usb_logging
  - board: xiao_ble//zmk
    shield: toucan_left rgbled_adapter nice_view_gem
    snippet: nrf52840-nosd studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: toucan_left_with_studio
  - board: xiao_ble//zmk
    shield: toucan_right rgbled_adapter
    snippet: nrf52840-nosd
  - board: xiao_ble//zmk
    shield: toucan_right rgbled_adapter
    snippet: nrf52840-nosd zmk-usb-logging
    cmake-args: >-
      -DCONFIG_INPUT_EVENT_DUMP=y
      -DCONFIG_ZMK_LOG_LEVEL_DBG=y
      -DCONFIG_INPUT_LOG_LEVEL_DBG=y
    artifact-name: toucan_right_debug
  - board: xiao_ble//zmk
    shield: settings_reset
    snippet: nrf52840-nosd
